Vagrant.configure("2") do |config|
  
  # MAIN vm with centos9, make and execute scripts here
  config.vm.define "main" do |main|
    main.vm.box = "generic/centos9s"

    main.vm.network "private_network", ip: "192.168.10.2"

    main.vm.provider "virutalbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end

    main.vm.provision "shell", inline: <<-SHELL
      hostnamectl set-hostname main
    SHELL
  end

  config.vm.define "server_centos" do |server_centos|
    server_centos.vm.box = "generic/centos9s"

    server_centos.vm.network "private_network", ip: "192.168.10.3"

    server_centos.vm.provision "shell", inline: <<-SHELL
      hostnamectl set-hostname servercentos
      sed -i '/s/PasswordAuthentication no/PasswordAuthentication yes' /etc/ssh/sshd_config
    SHELL
  end

  config.vm.define "server_debian" do |server_debian|
    server_debian.vm.box = "generic/debian10"

    server_debian.vm.network "private_network", ip: "192.168.10.4"

    server_debian.vm.provision "shell", inline: <<-SHELL
      hostnamectl set-hostname server_centos
    SHELL
  end

  
end
