version: '3.9'

services:
  selenium-firefox:
      image: selenium/standalone-firefox:4.8.2
      ports:
        - 4444:4444  
  selenium-chrome:
    image: selenium/standalone-chrome:4.8.2
    ports:
      - 4445:4444

networks:
  test:
    name: selenium_tests
    driver: bridge