version: '3.9'

services:
  monitor:
    image: alpine:3.16
    env_file:
      - .env
    build:
      context: .
      args:
        BASE_IMAGE_BUILDER: golang
        GOARCH: amd64
        GOARM:
    stdin_open: true
    tty: true
    volumes:
      -  ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro
      - ./config:/.config/jesseduffield/lazydocker
    