---
debian_docker_packages:
  - docker-ce 
  - docker-ce-cli 
  - containerd.io
  - docker-compose-plugin
  - docker-ce-rootless-extras

rhel_docker_packages:
  - docker-ce 
  - docker-ce-cli 
  - containerd.io
  - docker-compose-plugin
  - container-selinux
  - docker-ce-rootless-extras

users:
  - vagrant