version: '3.9'

services:
  v368:
    image: python:3.6.8
    restart: always
    # build:
      # context: .
    env_file:
      - .env
    volumes:
      - ./requirements.txt:/app/requirements.txt
    # entrypoint: "pip3 install -r /app/requirements.txt"
    command: "sleep infinity"
