version: '3.9'

services:
  db:
    image: postgres:${DB_VERSION}
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432


  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080