---
- name: Get all groups
  ansible.builtin.getent:
    database: group

# - name: Get all users
#   ansible.builtin.getent:
#     database: passwd

# - name: Debug
  # debug:
    # msg: '{{ item.groups | intersect(ansible_facts["getent_group"]) }}'
  # with_items: '{{ users }}'

- name: Create user
  ansible.builtin.user:
    name: '{{ item.username }}'
    home: '{{ item.home_dir }}'
    groups: '{{ item.groups | intersect(ansible_facts["getent_group"]) }}'
    shell: "/bin/bash"
    append: yes
  with_items: '{{ users }}'

- name: Set authorized keys
  ansible.posix.authorized_key:
    user: '{{ item.username }}'
    state: present
    key: "{% for key in item.authorized_keys %}{{ key ~ '\n' }}{% endfor %}"
  with_items: '{{ users }}'


