integrations:
  prometheus_remote_write:
  - basic_auth:
      password: {GCLOUD_RW_API_KEY}
      username: {GCLOUD_HOSTED_METRICS_ID}
    url: {GCLOUD_HOSTED_METRICS_URL}
  agent:
    enabled: true
    relabel_configs:
    - action: replace
      source_labels:
      - agent_hostname
      target_label: instance
    - action: replace
      target_label: job
      replacement: "integrations/agent-check"
    metric_relabel_configs:
    - action: keep
      regex: (prometheus_target_.*|prometheus_sd_discovered_targets|agent_build.*|agent_wal_samples_appended_total|process_start_time_seconds)
      source_labels:
      - __name__
  cadvisor:
    enabled: true
    docker_only: true
    instance: 'example_instance' # must match instance used in logs
    relabel_configs:
    - action: replace
      replacement: integrations/docker
      target_label: job
    metric_relabel_configs:
    - action: keep
      regex: container_cpu_usage_seconds_total|container_fs_inodes_free|container_fs_inodes_total|container_fs_limit_bytes|container_fs_usage_bytes|container_last_seen|container_memory_usage_bytes|container_network_receive_bytes_total|container_network_tcp_usage_total|container_network_transmit_bytes_total|container_spec_memory_reservation_limit_bytes|machine_memory_bytes|machine_scrape_error
      source_labels:
      - __name__
  # Add here any snippet that belongs to the `integrations` section.
  # For a correct indentation, paste snippets copied from Grafana Cloud at the beginning of the line.
logs:
  configs:
  - clients:
    - basic_auth:
        password: {GCLOUD_RW_API_KEY}
        username: {GCLOUD_HOSTED_LOGS_ID}
      url: {GCLOUD_HOSTED_LOGS_URL}
    name: integrations
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
    - job_name: integrations/docker
      docker_sd_configs:
        - host: unix:///var/run/docker.sock
        #- host: npipe:////./pipe/docker_engine #on windows
          refresh_interval: 5s
      relabel_configs:
      - action: replace
        replacement: integrations/docker
        target_label: job
      - action: replace
        replacement: 'example_instance' # must match instance used in cadvisor
        target_label: instance
      - source_labels:
          - __meta_docker_container_name
        regex: '/(.*)'
        target_label: container
      - source_labels: 
          - __meta_docker_container_log_stream
        target_label: stream

      # Add here any snippet that belongs to the `logs.configs.scrape_configs` section.
      # For a correct indentation, paste snippets copied from Grafana Cloud at the beginning of the line.
metrics:
  configs:
  - name: integrations
    remote_write:
    - basic_auth:
        password: {GCLOUD_RW_API_KEY}
        username: {GCLOUD_HOSTED_METRICS_ID}
      url: {GCLOUD_HOSTED_METRICS_URL}
    scrape_configs:
      # Add here any snippet that belongs to the `metrics.configs.scrape_configs` section.
      # For a correct indentation, paste snippets copied from Grafana Cloud at the beginning of the line.
  global:
    scrape_interval: {GCLOUD_SCRAPE_INTERVAL}
  wal_directory: /tmp/grafana-agent-wal
