version: '3.9'

services:
  agent:
    image: grafana/agent:main
    platform: linux/amd64
    env_file: .env
    volumes:
      - ./config.yaml:/etc/agent/agent.yaml
      - type: npipe
        source: \\.\pipe\docker_engine
        target: \\.\pipe\docker_engine