version: '3.9'

services:

  db:
    image: mysql:${DB_TAG}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD={MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE={MYSQL_DATABASE:-testowa}
      - MYSQL_USER={MYSQL_USER:-test}
      - MYSQL_PASSWORD={MYSQL_PASSWORD:-test}
    ports:
      - 3306:3306
    env_file:
      - ./.env
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080