version: '3.9'

services:

  db:
    image: mysql:${DB_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - 3306:3306
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080