version: '3.9'

services:

  db:
    image: mariadb:${DB_VERSION}
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-testowa}
      MARIADB_USER: ${MARIADB_USER:-test}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-test}
    ports:
      - 3306:3306
    env_file:
      - ./.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080