
version: '3.9'

services:
  php:
    image: webdevops/php-nginx:${TAG}
    env_file:
      - .env
    volumes:
      - ./provision/nginx/vhost.conf:/opt/docker/etc/nginx/vhost.conf
      - ./provision/cron/crontab:/etc/crontabs/application
      - ./provision/entrypoints/:/entrypoint.d/
    ports:
      - ${HTTPS_HOST_PORT:-8080}:80
      - ${HTTP_HOST_PORT:-8443}:433