version: '3.9'

networks:
  logmonitor_network:
    driver: bridge
    name: logmonitor_network
services:
  grafana:
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_LOG_LEVEL: "info"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/exanet_dashboard.json
    image: grafana/grafana:9.5.1
    networks:
      - logmonitor_network
    ports:
    - 3000:3000
    expose:
    - 3000
    restart: always
    volumes:
    - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
    - ./config/grafana/dashboards/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
    - ./config/grafana/dashboards/schemas/:/var/lib/grafana/dashboards:rw
    
  loki:
    command: -config.file=/etc/loki/loki-config.yml
    container_name: loki
    image: grafana/loki:2.8.0
    networks:
      - logmonitor_network
    restart: always
    volumes:
    - ./config/loki/loki-config.yaml:/etc/loki/loki-config.yml

  promtail:
    command: -config.file=/etc/promtail/promtail-config.yml
    container_name: promtail
    image: grafana/promtail:2.8.0
    networks:
      - logmonitor_network
    restart: always
    volumes:
    - ./config/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yml
  syslog-ng:
    command: -edv
    container_name: syslog-ng
    depends_on:
    - promtail
    image: balabit/syslog-ng:4.1.1
    networks:
      - logmonitor_network
    ports:
    - protocol: udp
      published: 514
      target: 514
    - protocol: tcp
      published: 5141
      target: 5141
    - protocol: udp
      published: 5152
      target: 5152
    - protocol: tcp
      published: 601
      target: 601
    restart: always
    volumes:
    - ./config/syslog-ng/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf

