apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld-container
        image: nginxdemos/hello
        ports:
        - name: helloworld-port
          containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
