apiVersion: v1
kind: Service
metadata:
  name: helloworld-loadbalancer
spec:
  ports:
    - port: 8090
      targetPort: helloworld-port
      protocol: TCP
  selector:
    app: helloworld
  type: LoadBalancer