apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  ports:
    - port: 8090
      nodePort: 30001
      targetPort: 80
      protocol: TCP
  selector:
    app: helloworld
  type: NodePort