apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  labels:
    app: helloworld
spec: 
  containers:
    - name: helloworld_container
      image: nginxdemos/hello
      ports: 
        - name: helloworld_port
          containerPort: 80