version: '3.9'

services:
  monitor:
    image: virtualzone/docker-container-stats
    container_name: docker-stats
    ports:
      - ${HOST_PORT:-8889}:8080
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro
      - ./db_stats:/opt/docker-stats/db
    