version: '3.9'

services:
  monitor:
    image: portainer/portainer-ce
    restart: 'no'
    ports:
      - ${HTTPS_HOST_PORT:-8890}:9443
      - ${HTTP_HOST_PORT:-8889}:9000
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: