version: '3.9'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: 'no'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${EXTERNAL_HTTPS_PORT}:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data