version: "3.9"

services:
  wiki:
    image: gollumwiki/gollum:master
    ports:
      - 4567:4567/tcp
    volumes:
      - /path/to/git/repo:/wiki/:rw
      # - ./provision/keys/id_rsa:/etc/wiki/github.pem
      - ./config/config.rb:/etc/gollum/config.rb
    command:
      - "--config=/etc/gollum/config.rb"
    restart: always