version: '3.9'

services:

  ubuntu:
    name: ubuntu-22.04
    image: ubuntu:22.04
    restart: 'no'
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    command: "sleep infinity"