- name: Set authorized keys
  ansible.posix.authorized_key:
    user: '{{ item.username }}'
    state: present
    key: "{% for key in item.authorized_keys %}{{ key ~ '\n' }}{% endfor %}"
  with_items: '{{ users }}'
