#Default credentials admin:admin
version: "3.9"

volumes:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-extensions:

services:
  sonarqube:
    image: sonarqube:10.0-community
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 9000:9000 #front
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions