---
# - name: Create user
#   hosts: webdev
#   become: yes
#   roles:
#     - create_user
# - name: Install common packages
#   hosts: 
#     - all
#     - localhost
#   become: yes
#   roles:
#     - common
#   tasks: 
#     - debug: 
#         msg: "{{ ansible_facts }}"
- name: Classic docker installation
  hosts: 
    - all
  become: yes
  roles:
    - docker
