{
 "title": "Exanet logs dashboard",
 "tags": [
  "exanet",
  "cisco",
  "syslog"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {}
   },
   { "name": "string_filter", "label": "String Filter" },
   {
    "name": "log_level",
    "label": "Log level",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Percentage of logs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({job=\"syslog\"} [$__range]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Percentage of type of logs",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"syslog\", level=~\"$log_level\", host=~\"$host\"} |= `$string_filter` [$__interval])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Count logs over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({job=\"syslog\", host=~\"$host\"} |= `$string_filter` [$__interval]))",
     "legendFormat": "{{host}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"syslog\", host=~\"$host\", level=~\"$log_level\"} |= `$string_filter`"
    }
   ]
  }
 ]
}