# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # box
  config.vm.box = "generic/debian11"
  # config.vm.box = "generic/ubuntu2004"

  # Disable automatic box update checking
  # config.vm.box_check_update = false

  # hostname
  config.vm.hostname = `pwd`.gsub(/.*[\/\\]/, '').gsub(/[^a-zA-Z0-9.-]/,'')

  # port forwarding
  #config.vm.network "forwarded_port", guest: 80, host: 8080     # HTTP
  #config.vm.network "forwarded_port", guest: 443, host: 8443    # HTTPS
  config.vm.network "forwarded_port", guest: 3000, host: 11000  # Grafana

  # private network NAT
  config.vm.network "private_network", ip: "10.13.8.5"

  # public network
  # config.vm.network "public_network"
  config.vm.network "public_network", bridge: "bridge0"
  
  # If true, then any SSH connections made will enable agent forwarding.
  # config.ssh.forward_agent = true

  # folder sharing/synchornization
  config.vm.synced_folder ".", "/vagrant", create: true, group: "vagrant", owner: "vagrant", mount_options: ["dmode=777", "fmode=777"]
  # config.vm.synced_folder ".", "/var/www/vagrant", create: true, group: "vagrant", owner: "vagrant"

  # Provider-specific configuration
  config.vm.provider "virtualbox" do |vb|
    # Don't boot with headless mode
    # vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "100"]
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
  end

  # provision by ansible
  config.vm.provision "ansible_local" do |ansible|
    ansible.verbose = true
    ansible.install = true
    ansible.playbook = "ansible/playbook.yml"
    ansible.galaxy_role_file = "ansible/requirements.yml"
    #
    # Select one or more tags, which describe serwer role. Some roles can be
    # customized further by extra vars in next step. Available tags:
    #
    # - 'python3; - Add Python 3
    ansible.tags = [
      "python3",
      "docker",
      "promtail_loki",
      "grafana",
      "syslog-ng"
    ]
    #
    # Extra vars are intended to setup selected tags. If tag is not selected,
    # associated extra vars are ignored. Available vars:
    #
    # - 'loki_version' - Loki version (available: 2.8.0)
    ansible.extra_vars = {
      loki_version: "2.8.0",
      syslogng_version: "4.1.1"
    }
  end

  # plugins
  config.vagrant.plugins = ["vagrant-vbguest"]

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = true
  end
end
